# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/fintech}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Raghav2816}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Scheduling
spring.task.scheduling.pool.size=5

# RestTemplate Timeouts
resttemplate.connect-timeout=3000
resttemplate.read-timeout=5000


# JWT
jwt.secret=${JWT_SECRET:finshield-super-secret-jwt-key-2024-which-is-long-enough-for-hs256-encryption-alg}
jwt.expiration=86400000



# Actuator
management.endpoints.web.exposure.include=health,info
